Add working pre receive hook

diff --git a/disable-large-commits b/disable-large-commits
--- a/disable-large-commits
+++ b/disable-large-commits
@@ -1,43 +1,42 @@
 #!/usr/bin/env bash
 
 #
-# Pre-receive hook that will block any new commits that contain files ending
-# with .gz, .zip or .tgz
-#
-# More details on pre-receive hooks and how to apply them can be found on
-# https://help.github.com/enterprise/admin/guides/developer-workflow/managing-pre-receive-hooks-on-the-github-enterprise-appliance/
+# Pre-receive hook that will block any new commits that contain files larger than 5Mb in size.
 #
 
 GITCMD="/usr/bin/git"
-NULLSHA="0000000000000000000000000000000000000000"
-MAXSIZE="5242880" # 5MB limit on file size
+zero_commit="0000000000000000000000000000000000000000"
+MAXSIZE="5000000" # 5MB limit on file size
 
 # Read stdin for ref information
-while read oldref newref refname; do
-  # Skip branch deletions
-  if [ "${newref}" = "${NULLSHA}" ]; then
-    continue;
-  fi
+while read oldrev newrev refname; do
+    # Skip branch deletions
+    if [ "${newrev}" = "${zero_commit}" ]; then
+        continue;
+    fi
 
-  # Set oldref properly if this is branch creation.
-  if [ "${oldref}" = "${NULLSHA}" ]; then
-    oldref="HEAD"
-  fi
+    # Set oldrev properly if this is branch creation.
+    if [ "${oldrev}" = "${zero_commit}" ]; then
+        oldrev="HEAD"
+    fi
 
-  # Get list of files to look at using git diff
-  for file in $($GITCMD diff --stat --name-only --diff-filter=ACMRT ${oldref}..${newref}); do
-    # Get the size of this file
-    size=$($GITCMD cat-file -s ${newref}:${file})
-	# Check to see if for some reason we didn't get a size
-    if [ ! -z ${size} ]; then
-      # Compare filesize to MAXSIZE
-      if [ "${size}" -gt "${MAXSIZE}" ]; then
-        # Send output back to the user about oversized files.
-        echo "ERROR: File ${file} larger than 5Mb. Please see Biocondcutor guidelines"
-        echo "    https://bioconductor.org/developers/package-guidelines/"
-        exit 1
-      fi # End size comparison
-    fi   # End check for empty size
-  done   # End list of files
+    # Get list of files to look at using git diff
+    for file in $($GITCMD diff --stat --name-only --diff-filter=ACMRT ${oldrev}..${newrev}); do
+        # Get the size of this file
+        size=$($GITCMD cat-file -s ${newrev}:${file})
+	    # Check to see if for some reason we didn't get a size
+        if [ ! -z ${size} ]; then
+            # Compare filesize to MAXSIZE
+            if [ "${size}" -gt "${MAXSIZE}" ]; then
+                # Send output back to the user about oversized files.
+                echo "Error: ${file} larger than 5Mb. Please see Biocondcutor guidelines"
+                echo "    https://bioconductor.org/developers/package-guidelines/"
+                # Fail here
+                exit 1
+            fi # End size comparison
+        fi   # End check for empty size
+    done   # End list of files
 done     # End reading stdin
+
+# If successful, pass
 exit 0
